### ISSUE TITLE
Zip file closed

### ISSUE THREAD

**Issue by ItsLiyua** [NathanCollaert/LiteDeathBan#15]
WHat does this error mean?
It happens on startup:
```
[11:52:52 ERROR]: Error occurred while enabling AugmentedHardcore v3.3.2 (Is it up to date?)

java.lang.IllegalStateException: zip file closed

	at java.util.zip.ZipFile.ensureOpen(Unknown Source) ~[?:?]

	at java.util.zip.ZipFile.getEntry(Unknown Source) ~[?:?]

	at java.util.jar.JarFile.getEntry(Unknown Source) ~[?:?]

	at java.util.jar.JarFile.getJarEntry(Unknown Source) ~[?:?]

	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:158) ~[patched_1.17.1.jar:git-Paper-314]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:108) ~[patched_1.17.1.jar:git-Paper-314]

	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[patched_1.17.1.jar:git-Paper-314]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:?]

	at com.backtobedrock.augmentedhardcore.configs.Configurations.getDeathBanConfiguration(Configurations.java:60) ~[AugmentedHardcore-3.3.2.jar:?]

	at com.backtobedrock.augmentedhardcore.configs.Configurations.<init>(Configurations.java:30) ~[AugmentedHardcore-3.3.2.jar:?]

	at com.backtobedrock.augmentedhardcore.AugmentedHardcore.initialize(AugmentedHardcore.java:136) ~[AugmentedHardcore-3.3.2.jar:?]

	at com.backtobedrock.augmentedhardcore.AugmentedHardcore.onEnable(AugmentedHardcore.java:63) ~[AugmentedHardcore-3.3.2.jar:?]

	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[patched_1.17.1.jar:git-Paper-314]

	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.17.1.jar:git-Paper-314]

	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:502) ~[patched_1.17.1.jar:git-Paper-314]

	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugin(CraftServer.java:544) ~[patched_1.17.1.jar:git-Paper-314]

	at org.bukkit.craftbukkit.v1_17_R1.CraftServer.enablePlugins(CraftServer.java:458) ~[patched_1.17.1.jar:git-Paper-314]

	at net.minecraft.server.MinecraftServer.loadWorld(MinecraftServer.java:725) ~[patched_1.17.1.jar:git-Paper-314]

	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:307) ~[patched_1.17.1.jar:git-Paper-314]

	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1212) ~[patched_1.17.1.jar:git-Paper-314]

	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[patched_1.17.1.jar:git-Paper-314]

	at java.lang.Thread.run(Unknown Source) ~[?:?]
```

**Comment by NathanCollaert** [comment]
Also, if this problem still exists, please try to 3.3.3-beta5 jar added below. Feel free to report back
[AugmentedHardcore-3.3.3-beta5.zip](https://github.com/NathanCollaert/AugmentedHardcore/files/7345824/AugmentedHardcore-3.3.3-beta5.zip)
!
