### ISSUE TITLE
Player gets an error on join after ban

### ISSUE THREAD

**Issue by Gamer57629** [NathanCollaert/LiteDeathBan#6]
Here is the error:
[WARNING] Failed to handle packet for /134.41.196.113:55362

java.lang.NullPointerException: null

at net.minecraft.server.v1_15_R1.PlayerList.attemptLogin(PlayerList.java:483) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]

at net.minecraft.server.v1_15_R1.LoginListener.c(LoginListener.java:134) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]

at net.minecraft.server.v1_15_R1.LoginListener.tick(LoginListener.java:53) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]

at net.minecraft.server.v1_15_R1.NetworkManager.a(NetworkManager.java:220) ~[spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]

at net.minecraft.server.v1_15_R1.ServerConnection.c(ServerConnection.java:129) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]

at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1105) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]

at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]

at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]

at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [spigot-1.15.2.jar:git-Spigot-2040c4c-893ad93]

at java.lang.Thread.run(Thread.java:813) [?:1.8.0_212]

[INFO] com.mojang.authlib.GameProfile@81ef4fea[id=dcb2e6eb-2249-43a5-85d2-fc9d2b37b3a6,name=action35,properties={textures=[com.mojang.authlib.properties.Property@9c6dbf5]},legacy=false] (/134.41.196.113:55362) lost connection: Internal server error

It's not game breaking and the player just has to rejoin again, but it is really annoying and I hope that you can get around to fixing it.

**Comment by NathanCollaert** [comment]
Hey there, unfortunately (fortunate for me) this error doesn't look like it has anything to do with the plugin LiteDeathBan. What caused you to think it was?

**Comment by Gamer57629** [comment]
I think that the plugin did cause the issue because when I disable it and ban then unban myself the error doesn't happen.

**Comment by NathanCollaert** [comment]
The error doesn't refer to the plugin LiteDeathBan in any way so that's weird. This error looks like a Spigot error that gets thrown when a player tries to connect to the server. Has this been happening since the beginning of the installation of the plugin or did it just start giving you this error now?
Does it happen which each player trying to reconnect or just periodically?

**Comment by Gamer57629** [comment]
The error has been happening since I installed the plugin and the it happens whenever a player reconnects after being unbanned.

**Comment by NathanCollaert** [comment]
I tried replicating this error but was unable to do so. I left the server and rejoined, no error. I DeathBanned myself, unbanned myself manually, no error. I DeathBanned myself and let the plugin automatically unban me, no error.
Are you able to communicate through Discord? Please add me if yes (Nathan#4444).
